---
# Debug...
# - template:
#     src: templates/network.xml.j2
#     dest: network.xml     

- name: Define network {{ cluster_name }}-baremetal-net
  include_tasks: create-network-internal.yml
  vars:
    vm_network_name: "{{ cluster_name }}-baremetal-net"
    vm_network_type: baremetal
    vm_subnet: "{{ vn_baremetal_subnet }}"

- name: Define network {{ cluster_name }}-provisioning-net
  include_tasks: create-network-internal.yml
  vars:
    vm_network_name: "{{ cluster_name }}-provisioning-net"
    vm_network_type: provisioning
    vm_subnet: "{{ vn_provisioning_subnet }}"
